#!/bin/bash

set -e

mkdir -p build

# IMPORTANT(Ryan): Initially populate CMakeCache.txt
# cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -Bbuild

cmake --build build -j $(getconf _NPROCESSORS_ONLN) >/dev/null

want_to_run=0
if [ $want_to_run -eq 1 ]; then
  mkdir -p run
  pushd run >/dev/null 

  ../build/niagara

  popd >/dev/null 
fi
