#!/bin/bash

set -e

mkdir -p build

# IMPORTANT(Ryan): Initially populate CMakeCache.txt
# cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -Bbuild

cmake --build build -j $(getconf _NPROCESSORS_ONLN) >/dev/null

pushd run >/dev/null 

../build/niagara

popd >/dev/null 
