#!/bin/bash

set -e

if [ $# -ge 1 ]; then
  if [ -f tags ]; then
    read -sn1 -p "Are you sure want to overwrite existing tags file? (y/n): " confirm
    echo
    if [ ! $confirm = "y" ]; then
      printf "Exitted without overwriting existing tags file.\n"
      exit 0
    fi
  fi
  rm -f tags
  find $* -type f -iname "*.[chS]" -o -iname "*.cpp" \
    | sudo xargs ctags --c-kinds=+lpx --c++-kinds=+lpx --fields=+iaS -a
  printf "Created tags file.\n"
else
  printf "Usage: search <folder1> [folder2] ...\n" >&2
fi
